blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from blogs import views as BlogsView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('category/', include('blogs.urls')),
    path('blogs/<slug:slug>', BlogsView.blogs, name='blogs'),
    path('blogs/search/', BlogsView.search, name='search'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    # Category CRUD
    path('categories/', views.categories, name='categories'),
    path('categories/add/', views.add_category, name='add_category'),
    path('categories/edit/<int:pk>', views.edit_category, name='edit_category'),
    path('categories/delete/<int:pk>',
         views.delete_category, name='delete_category'),

    # Blog Posts CRUD
    path('posts/', views.posts, name='posts'),
    path('posts/add/', views.add_post, name='add_post'),
    path('posts/edit/<int:pk>', views.edit_post, name='edit_post'),
    path('posts/delete/<int:pk>', views.delete_post, name='delete_post'),

    # Users
    path('users/', views.users, name='users'),
    path('users/add/', views.add_user, name='add_user'),
    path('users/edit/<int:pk>', views.edit_user, name='edit_user'),
    path('users/delete/<int:pk>', views.delete_user, name='delete_user')




]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name


STATUS_CHOICES = (
    ("Draft", "Draft"),
    ("Published", "Published")
)


class Blogs(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150, unique=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    featured_image = models.ImageField(upload_to='uploads/%y/%m/%d')
    short_description = models.TextField(max_length=500)
    blog_body = models.TextField(max_length=2000)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Draft")
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Blogs'

    def __str__(self):
        return self.title
    

dashboards/forms.py
from django import forms
from blogs.models import Blogs, Category
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = Blogs
        fields = ('title', 'category', 'featured_image',
                  'short_description', 'blog_body', 'status', 'is_featured')


class AddUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'is_active',
                  'is_staff', 'is_superuser', 'groups', 'user_permissions')


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'is_active',
                  'is_staff', 'is_superuser', 'groups', 'user_permissions')

dashboards/views.py
from django.shortcuts import redirect, render
from blogs.models import Category, Blogs
from django.contrib.auth.decorators import login_required
from .forms import BlogPostForm, CategoryForm, AddUserForm, EditUserForm
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


@login_required(login_url='login')
def dashboard(request):
    category_count = Category.objects.all().count()
    blogs_count = Blogs.objects.all().count()
    context = {
        'category_count': category_count,
        'blogs_count': blogs_count
    }
    return render(request, 'dashboard/dashboard.html', context)


def categories(request):
    return render(request, 'dashboard/categories.html')


def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('categories')
    form = CategoryForm()
    context = {
        'form': form
    }
    return render(request, 'dashboard/add_category.html', context)


def edit_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('categories')
    form = CategoryForm(instance=category)
    context = {
        'form': form,
        'category': category
    }
    return render(request, 'dashboard/edit_category.html', context)


def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    return redirect('categories')


def posts(request):
    posts = Blogs.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'dashboard/posts.html', context)


def add_post(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # save form temporarily
            post.author = request.user
            post.save()
            title = form.cleaned_data['title']
            post.slug = slugify(title)+'-'+str(post.id)
            post.save()
            return redirect('posts')
        else:
            print('form is invalid')
            print(form.errors)
    form = BlogPostForm()
    context = {
        'form': form
    }
    return render(request, 'dashboard/add_post.html', context)


def edit_post(request, pk):
    post = get_object_or_404(Blogs, pk=pk)
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            title = form.cleaned_data['title']
            post.slug = slugify(title) + '-' + str(post.id)
            post.save()
            return redirect('posts')
    form = BlogPostForm(instance=post)
    context = {
        'post': post,
        'form': form
    }
    return render(request, 'dashboard/edit_post.html', context)


def delete_post(request, pk):
    post = get_object_or_404(Blogs, pk=pk)
    post.delete()
    return redirect('posts')


def users(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'dashboard/users.html', context)


def add_user(request):
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users')
    form = AddUserForm()
    context = {
        'form': form
    }
    return render(request, 'dashboard/add_user.html', context)


def edit_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users')
    form = EditUserForm(instance=user)
    context = {
        'form': form,
        'user': user
    }
    return render(request, 'dashboard/edit_user.html', context)


def delete_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    user.delete()
    return redirect('users')

templates/dashboard/add_category.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side Bar -->
    <!-- load sidebar here -->
    {% include 'dashboard/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>Add New Category</h2>
        <form action="{% url 'add_category' %}" method="POST" style="width: 500;">
            {% csrf_token %}
            {{form | crispy}}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form><br>
    </div>
</div>
{% endblock %}

templates/dashboard/add_user.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side Bar -->
    <!-- load sidebar here -->
    {% include 'dashboard/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        {% if perms.auth.add_user %}
        <h2>Add New User</h2>
        <form action="{% url 'add_user' %}" method="POST" style="width: 500;">
            {% csrf_token %}
            {{form | crispy}}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form><br>
        {% else %}
        <h2>You don't have permissions to view this page</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/dashboard/categories.html
{% extends 'base.html' %}

{% block content%}
<div class="row">
    <!-- Left side Bar -->
    <!-- load sidebar here -->
    {% include 'dashboard/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        
        <h2>All Categories</h2>
        <a href="{% url 'add_category' %}" class="btn btn-dark text-light float-right mb-2">Add Category</a>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Category Name</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                <tr>
                    <th>{{forloop.counter}}</th>
                    <td>{{category.category_name}}</td>
                    <td>{{category.created_at}}</td>
                    <td>{{category.updated_at}}</td>
                    <td>
                        <a href="{% url 'edit_category' category.pk %}"><i class="fa fa-edit text-success"></i></a>
                        &nbsp;
                        <a href="{% url 'delete_category' category.pk %}"><i class="fa fa-trash text-danger"></i></a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        
    </div>
</div>
{% endblock %}

templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <!-- Left side Bar -->
    <!-- load sidebar here -->
    {% include 'dashboard/sidebar.html' %}

    <!-- Right side content -->
     <div class="col-md-9">
        
        <div class="row">

            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold">All Categories</div>
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{category_count}}</h5>
                    </div>
                    
                </div>
            </div>
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold">All Posts</div>
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{blogs_count}}</h5>
                    </div>
                    
                </div>
            </div>
        </div>
     </div>
</div>
{% endblock %}

templates/dashboard/edit_category.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side Bar -->
    <!-- load sidebar here -->
    {% include 'dashboard/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        {% if perms.auth.edit_category %}
        <h2>Edit Category</h2>
        <form action="{% url 'edit_category' category.id %}" method="POST" style="width: 500;">
            {% csrf_token %}
            {{form | crispy}}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form><br>
        {% else %}
        <h2>You don't have permissions to view this page</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/dashboard/edit_user.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side Bar -->
    <!-- load sidebar here -->
    {% include 'dashboard/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>Edit User</h2>
        <form action="{% url 'edit_user' user.id %}" method="POST" style="width: 500;" >
            {% csrf_token %}
            {{form | crispy}}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form><br>
    </div>
</div>
{% endblock %}

templates/dashboard/posts.html
{% extends 'base.html' %}

{% block content%}
<div class="row">
    <!-- Left side Bar -->
    <!-- load sidebar here -->
    {% include 'dashboard/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>All Posts</h2>
        <a href="{% url 'add_post' %}" class="btn btn-dark text-light float-right mb-2">Add Post</a>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Author</th>
                    <th>Status</th>
                    <th>Featured</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <th>{{forloop.counter}}</th>
                    <td>{{post.title}}</td>
                    <td>{{post.category}}</td>
                    <td>{{post.author}}</td>
                    <td>{{post.status}}</td>
                    <td>{% if post.is_featured %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
                    
                    <td>
                        <a href="{% url 'edit_post' post.id %}"><i class="fa fa-edit text-success"></i></a>
                        &nbsp;
                        <a href="{% url 'delete_post' post.id %}"><i class="fa fa-trash text-danger"></i></a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/dashboard/sidebar.html
<div class="col-md-3">
    <div class="nav flex-column nav-pills bg-white shadow rounded-4 p-3" aria-orientation="vertical">

        <a href="{% url 'dashboard' %}"
           class="nav-link fw-semibold rounded-3 mb-1
           {% if request.path == '/dashboard/' %}bg-primary text-white{% else %}text-dark{% endif %}">
            Dashboard
        </a>

        {% if perms.auth.view_user %}
        <a href="{% url 'users' %}"
           class="nav-link fw-semibold rounded-3 mb-1
           {% if '/users' in request.path %}bg-primary text-white{% else %}text-dark{% endif %}">
            Users
        </a>
        {% endif %}
        {% if perms.blogs.view_category %}
        <a href="{% url 'categories' %}"
           class="nav-link fw-semibold rounded-3 mb-1
           {% if '/categories' in request.path %}bg-primary text-white{% else %}text-dark{% endif %}">
            Categories
        </a>
        {% endif %}
        {% if perms.blogs.view_blogs %}
        <a href="{% url 'posts' %}"
           class="nav-link fw-semibold rounded-3 mb-1
           {% if '/posts' in request.path %}bg-primary text-white{% else %}text-dark{% endif %}">
            Posts
        </a>
        {% endif %}

        <hr class="my-2">

       
    </div>
</div>

templates/dashboard/users.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <!-- Left side Bar -->
    <!-- load sidebar here -->
    {% include 'dashboard/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        {% if perms.auth.view_user %}
        <h2>All Users</h2>
        <a href="{% url 'add_user' %}" class="btn btn-dark text-light float-right mb-2">Add User</a>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Full Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Active</th>
                    <th>Staff</th>
                    <th>Superuser</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <th>{{forloop.counter}}</th>
                    <td>{{user.first_name}} {{user.last_name}}</td>
                    <td>{{user.username}}</td>
                    <td>{{user.email}}</td>
                    <td>{% if user.is_active %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
                    <td>{% if user.is_staff %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
                    <td>{% if user.is_superuser %}<i class="fa fa-check text-success"></i>{% else %}<i class="fa fa-times text-danger"></i>{% endif %}</td>
                    <td>
                        <a href="{% url 'edit_user' user.id %}"><i class="fa fa-edit text-success"></i></a>
                        &nbsp;
                        <a href="{% url 'delete_user' user.id %}"><i class="fa fa-trash text-danger"></i></a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        {% else %}
        <h2>You dont have premission to view this page</h2>
        {% endif %}
    </div>
</div>
{% endblock %}